### PR TITLE
Remove minidom

### PR DESCRIPTION
**Pull request by tamird**
- **Remove dependency on minidom**
- **Bump quick-xml to 0.24.0**
- **Bump quick-xml to 0.32.0**
- **Bump quick-xml to 0.34.0**
- **Bump quick-xml to latest**

- - -
This change is [Reviewable](https://reviewable.io/reviews/tamird/pore/6)

### CODE REVIEW

**Comment by tamird** [comment]
@StefanBossbaly

**Review by StefanBossbaly — COMMENTED** [review]
Structure looks look, just need to fix `_` vs `-` in the serilaization

> *[Reviewable](https://reviewable.io/reviews/tamird/pore/6#-:-O7VDo2REzcc8gdwb6Hl:b-2gpmik)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @tamird)

___
*[`src/manifest/serializer.rs` line 73 at r1](https://reviewable.io/reviews/tamird/pore/6#-O7VDUym6I6XjyAwxWqH:-O7VDUym6I6XjyAwxWqI:butbbcp) ([raw file](https://github.com/tamird/pore/blob/a81064bf98820a46b67f2b96c76ecbc8773c377c/src/manifest/serializer.rs#L73)):*
> ```XML
>             populate_from_str_option(elem, "revision", &default.revision);
>             populate_from_str_option(elem, "remote", &default.remote);
>             populate_from_option(elem, "sync_j", &default.sync_j);
> ```

Should be `sync-j`

https://gerrit.googlesource.com/git-repo/+/HEAD/docs/manifest-format.md#Element-default
___
*[`src/manifest/serializer.rs` line 74 at r1](https://reviewable.io/reviews/tamird/pore/6#-O7VDbdR5TAH7Gzx5jmf:-O7VDbdR5TAH7Gzx5jmg:b12w4qa) ([raw file](https://github.com/tamird/pore/blob/a81064bf98820a46b67f2b96c76ecbc8773c377c/src/manifest/serializer.rs#L74)):*
> ```XML
>             populate_from_str_option(elem, "remote", &default.remote);
>             populate_from_option(elem, "sync_j", &default.sync_j);
>             populate_from_option(elem, "sync_c", &default.sync_c);
> ```

Should be `sync-c`

https://gerrit.googlesource.com/git-repo/+/HEAD/docs/manifest-format.md#Element-default

**Review by tamird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/6)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @StefanBossbaly)

___
*[`src/manifest/serializer.rs` line 73 at r1](https://reviewable.io/reviews/tamird/pore/6#-O7VDUym6I6XjyAwxWqH:-O7VWC4k7G2jF-svgq7X:b-896fix) ([raw file](https://github.com/tamird/pore/blob/a81064bf98820a46b67f2b96c76ecbc8773c377c/src/manifest/serializer.rs#L73)):*
<details><summary><i>Previously, StefanBossbaly (Stefan Bossbaly) wrote…</i></summary><blockquote>

Should be `sync-j`

https://gerrit.googlesource.com/git-repo/+/HEAD/docs/manifest-format.md#Element-default
</blockquote></details>

Done.
___
*[`src/manifest/serializer.rs` line 74 at r1](https://reviewable.io/reviews/tamird/pore/6#-O7VDbdR5TAH7Gzx5jmf:-O7VWBqiBoE02yGL7GFO:b-896fix) ([raw file](https://github.com/tamird/pore/blob/a81064bf98820a46b67f2b96c76ecbc8773c377c/src/manifest/serializer.rs#L74)):*
<details><summary><i>Previously, StefanBossbaly (Stefan Bossbaly) wrote…</i></summary><blockquote>

Should be `sync-c`

https://gerrit.googlesource.com/git-repo/+/HEAD/docs/manifest-format.md#Element-default
</blockquote></details>

Done.

**Review by StefanBossbaly — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/6#-:-O7VXeknAbp9dNh-E48l:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @tamird)

**Pull request merged**
