### PR TITLE
Added branches subcommand

### PR DESCRIPTION
**Pull request by StefanBossbaly**
Added the branches subcommand which will print out all projects that have a topic branch in their repo. This makes it very easy to find which repos have what topic branches and pairs with the checkout subcommand which allows developers to easily switch between their cross repo changes and check on the status of these changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tamird/pore/2)

### CODE REVIEW

**Review by tamird — CHANGES_REQUESTED** [review]
:lgtm: with comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O74qd6r-PVWEXNkg7HM:b-oit4a9)* status: all files reviewed, 2 unresolved discussions (waiting on @StefanBossbaly)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74pl4507u_tU-_vd26):*
same as #1 - link to the relevant repo command?
___
*[`src/main.rs` line 481 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74prPe4KON-ERYNKX_:-O74prPe4KON-ERYNKXa:b-j3hp8u) ([raw file](https://github.com/tamird/pore/blob/afad776d3322849b5ca36e79c1d052b581bac014/src/main.rs#L481)):*
> ```XML
>           })
>           .collect::<Vec<_>>()
>           .join(", ")
> ```

we already have a dep on [joinery)(https://docs.rs/joinery/latest/joinery/), we shouldn't need to materialize this vector. 
___
*[`src/tree.rs` line 1188 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74qVsC7-UFQOmMQ5gd:-O74qVsC7-UFQOmMQ5ge:b-ta2cax) ([raw file](https://github.com/tamird/pore/blob/afad776d3322849b5ca36e79c1d052b581bac014/src/tree.rs#L1188)):*
> ```XML
>         move || -> Result<ProjectBranchStatus, Error> {
>           let repo = git2::Repository::open(self.path.join(&project.project_path))
>             .context(format!("failed to open object repository {:?}", project.project_path))?;
> ```

FYI `context(format!(...))` is a bad pattern that allocates strings even in the OK case. I'll boil the ocean at some point.

**Review by StefanBossbaly — COMMENTED** [review]
Fixed all issues

> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O74vQNg4Qlk1vjB2qoN:b-6be5jq)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tamird)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74pl4507u_tU-_vd26):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

same as #1 - link to the relevant repo command?
</blockquote></details>

Added link to [`branches`](https://android.googlesource.com/tools/repo/+/refs/heads/main/subcmds/branches.py) in commit message.
___
*[`src/main.rs` line 481 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74prPe4KON-ERYNKX_:-O74uSk52fRSjlWTJ2Bi:b-886gsx) ([raw file](https://github.com/tamird/pore/blob/afad776d3322849b5ca36e79c1d052b581bac014/src/main.rs#L481)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

we already have a dep on [joinery)(https://docs.rs/joinery/latest/joinery/), we shouldn't need to materialize this vector.
</blockquote></details>

Fixed
___
*[`src/tree.rs` line 1188 at r1](https://reviewable.io/reviews/tamird/pore/2#-O74qVsC7-UFQOmMQ5gd:-O74uQcZA7jYaycnsdMC:b-886gsx) ([raw file](https://github.com/tamird/pore/blob/afad776d3322849b5ca36e79c1d052b581bac014/src/tree.rs#L1188)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

FYI `context(format!(...))` is a bad pattern that allocates strings even in the OK case. I'll boil the ocean at some point.
</blockquote></details>

Fixed

**Review by tamird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O74vzLZ7s8BF2PBzhv8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @StefanBossbaly)

___
*[`src/main.rs` line 477 at r2](https://reviewable.io/reviews/tamird/pore/2#-O74vwHn3vHHu87KrRsl:-O74vwHn3vHHu87KrRsm:b-b6z9f1) ([raw file](https://github.com/tamird/pore/blob/6418b2c7a4c26f56bac0d7e6222faf2eb629b9c5/src/main.rs#L477)):*
> ```XML
>               format!("*{}", branch.name)
>             } else {
>               branch.name.clone()
> ```

this can be avoided using Cow
___
*[`src/tree.rs` line 1205 at r2](https://reviewable.io/reviews/tamird/pore/2#-O74voVT5zyYAnB6wkZp:-O74voVT5zyYAnB6wkZq:b-uu6a7c) ([raw file](https://github.com/tamird/pore/blob/6418b2c7a4c26f56bac0d7e6222faf2eb629b9c5/src/tree.rs#L1205)):*
> ```XML
> 
>           Ok(ProjectBranchStatus {
>             name: project.project_name.clone(),
> ```

you shouldn't have to clone here *and* above

**Review by StefanBossbaly — COMMENTED** [review]
Implemented all suggestions

> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O750nXJD3sSX1PYVGPm:bdmtfv1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tamird)

___
*[`src/main.rs` line 477 at r2](https://reviewable.io/reviews/tamird/pore/2#-O74vwHn3vHHu87KrRsl:-O750Kb48h62dF1bNevg:b-886gsx) ([raw file](https://github.com/tamird/pore/blob/6418b2c7a4c26f56bac0d7e6222faf2eb629b9c5/src/main.rs#L477)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this can be avoided using Cow
</blockquote></details>

Fixed
___
*[`src/tree.rs` line 1205 at r2](https://reviewable.io/reviews/tamird/pore/2#-O74voVT5zyYAnB6wkZp:-O750lT_06pjl4B-ARv6:b-886gsx) ([raw file](https://github.com/tamird/pore/blob/6418b2c7a4c26f56bac0d7e6222faf2eb629b9c5/src/tree.rs#L1205)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you shouldn't have to clone here *and* above
</blockquote></details>

Fixed

**Review by tamird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O751xo-0iHaiwWJNdgc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StefanBossbaly)

**Comment by tamird** [comment]
I think I broke you again, could you rebase?

**Review by StefanBossbaly — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2#-:-O7574sD7B3HrylGu8K4:bb6un1j)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @tamird)

**Review by tamird — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tamird/pore/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StefanBossbaly)

**Pull request merged**
